services:
  - type: web
    name: fastapi-backend
    env: python
    buildCommand: ""
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    plan: free
    runtime: python
    region: oregon
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        value: postgresql://cards_db_ka8q_user:oJ8c77zdqnrsrgAPT7TlQSoqTAvXLiBt@dpg-d0a58kjuibrs73augn2g-a/cards_db_ka8q
